#!/usr/bin/env bash
# Runs inside the Ubuntu 22.04 container.
# Source is mounted at /src; only /src/build/bin/linux/GlideFTP-Debian-x86_64-v<version>.AppImage
# is written back to the host.
set -e

VERSION="${1:?Usage: build-appimage.sh <version>}"

WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

echo "   [debian] Copying source…"
rsync -a \
    --exclude='.git' \
    --exclude='frontend/node_modules' \
    --exclude='build/bin' \
    --exclude='tools' \
    --exclude='.claude' \
    /src/ "$WORKDIR/"

cd "$WORKDIR"

echo "   [debian] Building wails binary…"
wails build -tags webkit2_41

APPDIR="$(mktemp -d)/GlideFTP.AppDir"
mkdir -p "$APPDIR/usr/bin"
cp build/bin/GlideFTP "$APPDIR/usr/bin/"

convert build/appicon.png -resize 256x256 "$APPDIR/glideftp.png"

cat > "$APPDIR/glideftp.desktop" << 'DESKTOP'
[Desktop Entry]
Type=Application
Name=GlideFTP
Exec=GlideFTP
Icon=glideftp
Categories=Network;FileTransfer;
Comment=FTP/SFTP desktop client
DESKTOP

echo "   [debian] Bundling libs (webkit helpers excluded — added manually below)…"
# Deploy libs only — no --output so we can patch AppRun before packaging
linuxdeploy \
    --appdir "$APPDIR" \
    --desktop-file "$APPDIR/glideftp.desktop" \
    --icon-file "$APPDIR/glideftp.png"

# webkit2gtk helper processes are executables, not .so — linuxdeploy misses them.
# webkit looks for them at the path hardcoded at compile time; we override that
# via WEBKIT_EXEC_PATH so it finds the bundled copies instead.
WEBKIT_SRC="/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1"
WEBKIT_DST="$APPDIR/usr/lib/webkit2gtk-4.1"
mkdir -p "$WEBKIT_DST"
for helper in WebKitNetworkProcess WebKitWebProcess; do
    [ -f "$WEBKIT_SRC/$helper" ] && cp "$WEBKIT_SRC/$helper" "$WEBKIT_DST/"
done

# Patch AppRun (generated by linuxdeploy) to export WEBKIT_EXEC_PATH before exec
awk '
/^exec / {
    print "export WEBKIT_EXEC_PATH=\"${HERE}/usr/lib/webkit2gtk-4.1\""
}
{ print }
' "$APPDIR/AppRun" > /tmp/AppRun.patched
mv /tmp/AppRun.patched "$APPDIR/AppRun"
chmod +x "$APPDIR/AppRun"

echo "   [debian] Packaging AppImage…"
export OUTPUT="/tmp/GlideFTP-Debian-x86_64.AppImage"
ARCH=x86_64 linuxdeploy-plugin-appimage --appdir "$APPDIR"

mkdir -p /src/build/bin/linux
DEST="/src/build/bin/linux/GlideFTP-Debian-x86_64-v${VERSION}.AppImage"
mv "$OUTPUT" "$DEST"

# Restore host ownership so the file isn't root-owned on the host
if [ -n "${HOST_UID:-}" ] && [ -n "${HOST_GID:-}" ]; then
    chown "${HOST_UID}:${HOST_GID}" "$DEST"
fi
