#!/usr/bin/env python3
"""
Generates the soft notification sounds bundled with GlideFTP (played when a
transfer finishes, see internal/settings + frontend/src/utils/sound.js).

Pure Python stdlib (wave/struct/math) - no external dependencies. Produces
short, gentle tones (soft attack, exponential decay, moderate peak level)
so none of them are jarring. Output:
  - frontend/src/assets/sounds/*.wav             (reference files, for listening)
  - frontend/src/utils/sounds.generated.js        (base64 data: URLs, actually used by the app)

The .wav files are NOT imported by the app directly: WebKitGTK's <audio>
element loader only recognizes a fixed set of URI schemes (http/https/file/
data/blob/...). Wails serves the frontend through its own custom `wails://`
scheme, which isn't in that list, so a plain asset URL fails instantly with
a GStreamer-less "FormatError" - before any playback is even attempted, in
both `wails dev` and the compiled binary. Embedding each sound as a
`data:audio/wav;base64,...` string sidesteps the scheme check entirely, and
works identically in dev and build (unlike Vite's `?inline`/assetsInlineLimit
asset-URL inlining, which Vite 3 - pinned by this project - doesn't apply to
its dev server).

Re-run after tweaking a synth definition below:
    python3 scripts/generate_notification_sounds.py
"""
import base64
import io
import math
import os
import struct
import wave

SR = 44100
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "frontend", "src", "assets", "sounds")
JS_OUT = os.path.join(os.path.dirname(__file__), "..", "frontend", "src", "utils", "sounds.generated.js")


def envelope(t, attack, decay_tau):
    if t < attack:
        return t / attack
    return math.exp(-(t - attack) / decay_tau)


def make_tone(freq, duration, decay_tau, attack=0.006, harmonics=((1, 1.0), (2, 0.28), (3, 0.12))):
    """One damped tone with a small stack of (possibly inharmonic) overtones."""
    n = int(SR * duration)
    out = [0.0] * n
    for i in range(n):
        t = i / SR
        env = envelope(t, attack, decay_tau)
        v = 0.0
        for mult, amp in harmonics:
            v += amp * math.sin(2 * math.pi * freq * mult * t)
        out[i] = v * env
    return out


def mix(tracks_with_offsets):
    """tracks_with_offsets: list of (samples, offset_seconds)."""
    total_len = max(len(s) / SR + off for s, off in tracks_with_offsets)
    n = int(SR * total_len) + 1
    out = [0.0] * n
    for samples, off in tracks_with_offsets:
        start = int(off * SR)
        for i, v in enumerate(samples):
            idx = start + i
            if idx < n:
                out[idx] += v
    return out


def render_wav_bytes(samples, peak=0.55, fade_ms=12):
    m = max(abs(x) for x in samples) or 1.0
    scale = peak / m
    n = len(samples)
    fade = int(SR * fade_ms / 1000)
    frames = bytearray()
    for i, x in enumerate(samples):
        v = x * scale
        if i > n - fade:
            v *= max(0.0, (n - i) / fade)
        v = max(-1.0, min(1.0, v))
        frames += struct.pack("<h", int(v * 32767))
    buf = io.BytesIO()
    with wave.open(buf, "w") as f:
        f.setnchannels(1)
        f.setsampwidth(2)
        f.setframerate(SR)
        f.writeframes(bytes(frames))
    return buf.getvalue()


def write_wav(path, samples, peak=0.55, fade_ms=12):
    data = render_wav_bytes(samples, peak=peak, fade_ms=fade_ms)
    with open(path, "wb") as f:
        f.write(data)
    print(f"wrote {path} ({len(samples) / SR:.2f}s)")
    return data


def build_chime():
    # Two soft ascending bell-like notes (C6 -> E6), slightly overlapping.
    n1 = make_tone(1046.50, 0.55, 0.30, harmonics=((1, 1.0), (2, 0.30), (3, 0.12), (4, 0.05)))
    n2 = make_tone(1318.51, 0.60, 0.34, harmonics=((1, 1.0), (2, 0.30), (3, 0.12), (4, 0.05)))
    return mix([(n1, 0.0), (n2, 0.13)])


def build_bell():
    # A single warm, long-decaying bell (A5) with soft inharmonic overtones.
    return make_tone(
        880.0, 1.3, 0.85, attack=0.004,
        harmonics=((1, 1.0), (2.01, 0.35), (2.7, 0.18), (4.2, 0.07)),
    )


def build_pop():
    # A very short, soft wood-block/marimba-like blip (C5).
    return make_tone(
        523.25, 0.28, 0.085, attack=0.003,
        harmonics=((1, 1.0), (2.4, 0.22), (4.1, 0.06)),
    )


def build_glass():
    # Airy, bright-but-soft descending two-note (E6 -> C6).
    n1 = make_tone(1318.51, 0.45, 0.28, harmonics=((1, 0.6), (2, 0.5), (3, 0.25), (4, 0.1)))
    n2 = make_tone(1046.50, 0.55, 0.36, harmonics=((1, 0.6), (2, 0.5), (3, 0.25), (4, 0.1)))
    return mix([(n1, 0.0), (n2, 0.16)])


def write_js_module(sounds):
    lines = [
        "// AUTO-GENERATED by scripts/generate_notification_sounds.py - do not edit by hand.",
        "// Each value is a self-contained data: URI (see the script for why - WebKitGTK's",
        "// <audio> loader rejects Wails' custom `wails://` asset scheme).",
        "export const SOUND_DATA_URLS = {",
    ]
    for name, data in sounds:
        b64 = base64.b64encode(data).decode("ascii")
        lines.append(f'  {name}: "data:audio/wav;base64,{b64}",')
    lines.append("};")
    with open(JS_OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {JS_OUT}")


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    sounds = [
        ("chime", write_wav(os.path.join(OUT_DIR, "chime.wav"), build_chime())),
        ("bell", write_wav(os.path.join(OUT_DIR, "bell.wav"), build_bell())),
        ("pop", write_wav(os.path.join(OUT_DIR, "pop.wav"), build_pop())),
        ("glass", write_wav(os.path.join(OUT_DIR, "glass.wav"), build_glass())),
    ]
    write_js_module(sounds)


if __name__ == "__main__":
    main()
