// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseLocalDir() {
  return window['go']['main']['App']['BrowseLocalDir']();
}

export function BrowseSSHKey() {
  return window['go']['main']['App']['BrowseSSHKey']();
}

export function CancelTransfer(arg1) {
  return window['go']['main']['App']['CancelTransfer'](arg1);
}

export function ClearTransfers(arg1) {
  return window['go']['main']['App']['ClearTransfers'](arg1);
}

export function CloseConnection(arg1) {
  return window['go']['main']['App']['CloseConnection'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function ConnectAdditional(arg1) {
  return window['go']['main']['App']['ConnectAdditional'](arg1);
}

export function ConnectToSite(arg1) {
  return window['go']['main']['App']['ConnectToSite'](arg1);
}

export function ConnectToSiteAdditional(arg1, arg2) {
  return window['go']['main']['App']['ConnectToSiteAdditional'](arg1, arg2);
}

export function ConnectWithPassword(arg1, arg2) {
  return window['go']['main']['App']['ConnectWithPassword'](arg1, arg2);
}

export function CreateSite(arg1) {
  return window['go']['main']['App']['CreateSite'](arg1);
}

export function DeleteSite(arg1) {
  return window['go']['main']['App']['DeleteSite'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DoImportSites(arg1, arg2) {
  return window['go']['main']['App']['DoImportSites'](arg1, arg2);
}

export function ExpandLocalPath(arg1) {
  return window['go']['main']['App']['ExpandLocalPath'](arg1);
}

export function ExportSettings() {
  return window['go']['main']['App']['ExportSettings']();
}

export function ExportSitesEncrypted(arg1) {
  return window['go']['main']['App']['ExportSitesEncrypted'](arg1);
}

export function ExportSitesEncryptedSelected(arg1, arg2) {
  return window['go']['main']['App']['ExportSitesEncryptedSelected'](arg1, arg2);
}

export function ExportSitesPlain() {
  return window['go']['main']['App']['ExportSitesPlain']();
}

export function ExportSitesPlainSelected(arg1) {
  return window['go']['main']['App']['ExportSitesPlainSelected'](arg1);
}

export function GetActiveConnectionID() {
  return window['go']['main']['App']['GetActiveConnectionID']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetKeyringStatus() {
  return window['go']['main']['App']['GetKeyringStatus']();
}

export function GetLocalHome() {
  return window['go']['main']['App']['GetLocalHome']();
}

export function GetLocalParent(arg1) {
  return window['go']['main']['App']['GetLocalParent'](arg1);
}

export function GetLocalRoots() {
  return window['go']['main']['App']['GetLocalRoots']();
}

export function GetRemoteCwd() {
  return window['go']['main']['App']['GetRemoteCwd']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSites() {
  return window['go']['main']['App']['GetSites']();
}

export function GetTransfers() {
  return window['go']['main']['App']['GetTransfers']();
}

export function ImportSettings() {
  return window['go']['main']['App']['ImportSettings']();
}

export function LocalCopy(arg1, arg2) {
  return window['go']['main']['App']['LocalCopy'](arg1, arg2);
}

export function LocalDelete(arg1) {
  return window['go']['main']['App']['LocalDelete'](arg1);
}

export function LocalListDir(arg1) {
  return window['go']['main']['App']['LocalListDir'](arg1);
}

export function LocalMkDir(arg1) {
  return window['go']['main']['App']['LocalMkDir'](arg1);
}

export function LocalRename(arg1, arg2) {
  return window['go']['main']['App']['LocalRename'](arg1, arg2);
}

export function LocalSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['LocalSearch'](arg1, arg2, arg3);
}

export function OpenImportDialog() {
  return window['go']['main']['App']['OpenImportDialog']();
}

export function QueueDownload(arg1, arg2) {
  return window['go']['main']['App']['QueueDownload'](arg1, arg2);
}

export function QueueDownloadDir(arg1, arg2) {
  return window['go']['main']['App']['QueueDownloadDir'](arg1, arg2);
}

export function QueueUpload(arg1, arg2) {
  return window['go']['main']['App']['QueueUpload'](arg1, arg2);
}

export function QueueUploadDir(arg1, arg2) {
  return window['go']['main']['App']['QueueUploadDir'](arg1, arg2);
}

export function RemoteCopy(arg1, arg2) {
  return window['go']['main']['App']['RemoteCopy'](arg1, arg2);
}

export function RemoteCopyDir(arg1, arg2) {
  return window['go']['main']['App']['RemoteCopyDir'](arg1, arg2);
}

export function RemoteDelete(arg1) {
  return window['go']['main']['App']['RemoteDelete'](arg1);
}

export function RemoteListDir(arg1) {
  return window['go']['main']['App']['RemoteListDir'](arg1);
}

export function RemoteMkDir(arg1) {
  return window['go']['main']['App']['RemoteMkDir'](arg1);
}

export function RemoteRename(arg1, arg2) {
  return window['go']['main']['App']['RemoteRename'](arg1, arg2);
}

export function RemoteSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoteSearch'](arg1, arg2, arg3);
}

export function RemoveTransfer(arg1) {
  return window['go']['main']['App']['RemoveTransfer'](arg1);
}

export function ReorderSites(arg1) {
  return window['go']['main']['App']['ReorderSites'](arg1);
}

export function RetryTransfer(arg1) {
  return window['go']['main']['App']['RetryTransfer'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SwitchConnection(arg1) {
  return window['go']['main']['App']['SwitchConnection'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateSite(arg1) {
  return window['go']['main']['App']['UpdateSite'](arg1);
}
