// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connection} from '../models';
import {sites} from '../models';
import {fs} from '../models';
import {settings} from '../models';
import {transfer} from '../models';

export function BrowseLocalDir():Promise<string>;

export function BrowseSSHKey():Promise<string>;

export function CancelTransfer(arg1:string):Promise<void>;

export function ClearTransfers(arg1:string):Promise<void>;

export function Connect(arg1:connection.Config):Promise<void>;

export function ConnectToSite(arg1:string):Promise<void>;

export function ConnectWithPassword(arg1:string,arg2:string):Promise<void>;

export function CreateSite(arg1:sites.Site):Promise<sites.Site>;

export function DeleteSite(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function ExportSites():Promise<void>;

export function GetConnectionStatus():Promise<string>;

export function GetLocalHome():Promise<string>;

export function GetLocalParent(arg1:string):Promise<string>;

export function GetLocalRoots():Promise<Array<fs.FileEntry>>;

export function GetRemoteCwd():Promise<string>;

export function GetSettings():Promise<settings.Settings>;

export function GetSites():Promise<Array<sites.Site>>;

export function GetTransfers():Promise<Array<transfer.Job>>;

export function ImportSites():Promise<number>;

export function LocalDelete(arg1:string):Promise<void>;

export function LocalListDir(arg1:string):Promise<Array<fs.FileEntry>>;

export function LocalMkDir(arg1:string):Promise<void>;

export function LocalRename(arg1:string,arg2:string):Promise<void>;

export function QueueDownload(arg1:string,arg2:string):Promise<void>;

export function QueueUpload(arg1:string,arg2:string):Promise<void>;

export function RemoteDelete(arg1:string):Promise<void>;

export function RemoteListDir(arg1:string):Promise<Array<connection.RemoteFileEntry>>;

export function RemoteMkDir(arg1:string):Promise<void>;

export function RemoteRename(arg1:string,arg2:string):Promise<void>;

export function RemoveTransfer(arg1:string):Promise<void>;

export function RetryTransfer(arg1:string):Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function UpdateSite(arg1:sites.Site):Promise<void>;
